#Sys.setenv(GITHUB_PAT = "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")
print('immunogenomics/presto')
remotes::install_github("immunogenomics/presto", upgrade='never')
print('Matrix')
remotes::install_version("Matrix",version = "1.6-1.1", INSTALL_opts = '--no-lock', force=TRUE, upgrade='never')
print('SeuratObject')
remotes::install_version("SeuratObject", "4.1.4", repos = c("https://satijalab.r-universe.dev", getOption("repos")), upgrade='never')
print('Seurat')
remotes::install_version(package = 'Seurat', version = package_version('4.4.0'), upgrade='never')
#remotes::install_github('satijalab/seurat-data', quiet = TRUE)
print('seqyuan/s4wrapper')
remotes::install_github('seqyuan/s4wrapper')
#remotes::install_github('satijalab/seurat-wrappers', quiet = TRUE, upgrade='never')
#remotes::install_github('YuLab-SMU/clusterProfiler', upgrade='never')
print('junjunlab/scRNAtoolVis')
remotes::install_github('junjunlab/scRNAtoolVis', upgrade='never')
remotes::install_github("sajuukLyu/ggunchull", type = "source", upgrade='never')
remotes::install_github('mojaveazure/seurat-disk', upgrade='never')

